### ISSUE TITLE
Add more fonts

### ISSUE THREAD

**Issue by waterrmalann** [waterrmalann/fancy-fonts-generator#3]
It would be much better if more fonts could be added to the generator. Especially with the introduction of support for arrays in the [`fonts.json`](https://github.com/waterrmalann/fancy-fonts-generator/blob/main/fonts.json) file in [`#19043d7`](https://github.com/waterrmalann/fancy-fonts-generator/commit/19043d723c55e0b82448152715ad9b955d10525b), this opens new up possibilities for more complex multi-character pseudo fonts. 

I've already compiled an unnamed list of potential pseudofonts in [`potential_fonts.txt`](https://github.com/waterrmalann/fancy-fonts-generator/files/9633276/potential_fonts.txt) that could make it into the generator. Some of them are multi-character per letter and will need to use the array-based syntax. They need to be given unique names and added to the fonts.json file. 

The list may contain duplicates of fonts already in the current fonts.json file, I haven't done any cross-checking yet.

**Comment by katieleebrown** [comment]
Hi @waterrmalann , I'd love to help out with adding in and cross checking your fonts!
